# Extra autostart processes
#exec-once = uwsm-app -- my-service
exec-once = hyprpm reload && hyprctl dismissnotify
exec-once = XDG_MENU_PREFIX=arch- kbuildsycoca6
exec-once = /usr/bin/openrgb --startminimized
exec-once = wayvnc
exec-once = hyprctl setcursor Layan-border-cursors 32 
exec-once = hyprctl dispatch movecursor 5120 1440
exec-once = /home/$USER/http/nut_webgui/nut_webgui/target/release/nut_webgui -p 9000 --default-theme forest --upsd-user admin --upsd-pass $(cat /home/$USER/.nut_passwd)
exec-once = hyprctl dispatch movecursor 2560 720 
exec-once = OMARCHY_LOCK_ONLY=true omarchy system lock
exec-once = eww open logo
exec-once = eww open desktop
#exec-once = /home/$USER/scripts/start_openrgb.sh
exec-once = ~/.mas/Markuse\ asjad/Markuse\ arvuti\ integratsioonitarkvara & disown
exec-once = ~/.mas/Markuse\ asjad/MasAPI & disown
#exec-once = sleep 2 && aplay --device=hdmi:CARD=HDMI,DEV=0 /home/$USER/.mas/startup_linux.wav
