# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
# broken for some reason?
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
#source = ~/.config/hypr/looknfeel_default.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/plugins.conf

# Add any other personal Hyprland configuration below
windowrule = workspace 5, match:class qemu
windowrule = float on, center on, match:class Markuse arvuti juhtpaneel
#windowrule = hyprbars:no_bar on, match:class thunar
#windowrule = hyprbars:no_bar on, match:class floorp
windowrule = float on, center on, match:class FlipnicFileToolGUI
#windowrule = hyprbars:no_bar on, match:class Xdg-desktop-portal-gtk
windowrule = float on, center on, match:class com.system76.CosmicFilesDialog
windowrule = float on, center on, match:class MainKt
#windowrule = hyprbars:no_bar on, match:class jetbrains-rider, match:title splash
#windowrule = hyprbars:no_bar on, match:class jetbrains-rider, match:title Confirm Exit
#windowrule = hyprbars:no_bar on, match:class winboat
windowrule =  opacity 50, float on, no_vrr on, no_anim on, no_blur on, no_dim on, no_follow_mouse on, no_shadow on, opaque on, immediate on, render_unfocused on, xray on, force_rgbx off, rounding 0, match:class (winboat)(.*)
#windowrule = hyprbars:no_bar on, match:class org.telegram.desktop
#windowrule = hyprbars:no_bar on, match:class flashpoint-launcher
#windowrule = hyprbars:no_bar on, match:fullscreen_state_client 2
windowrule = content none, match:class ^(pcsx2)$
windowrule = match:modal focus:0
windowrule = float on, center on, dim_around on, no_vrr on, min_size 800 600, match:class org.freedesktop.impl.portal.desktop.kde
windowrule = float on, center on, dim_around on, no_vrr on, min_size 800 600, match:class com.system76.CosmicFilesDialog
windowrule = size 800 600, match:class org.omarchy.bash
windowrule = stay_focused on, match:initial_title ^RemoteApp
windowrule = no_follow_mouse on, focus_on_activate off, match:class ^(cheatengine-x86_64-sse4-avx2.exe)$
windowrule = opacity 0, match:class invis
windowrule = no_vrr on, fullscreen on, match:class ^(explorer.exe)$
windowrule = no_vrr on, match:class ^(xfreerdp)$
animation = windows, 1, 8, default, slidefade 20%

# Toggle config flags dynamically
#source = ~/.local/state/omarchy/toggles/hypr/*.conf
