source = ~/.config/omarchy/current/theme/hyprlock.conf
 
general {
    ignore_empty_input = false
}

background {
    monitor =
    color = $color
    path = ~/.mas/bg_login.png
    blur_passes = 0
}

label {
    text = cmd[update:1000] echo "$(date +%H:%M)"
    position = 0, -9
    valign = top
    font_family = REM
    font_size = 18
    color = rgba(255, 255, 255, 1.0)
    shadow_passes = 3
    shadow_boost = 0.9
}

label {
    text = Salasõna
    position = -150, -100
    valign = center
    font_family = REM
    font_size = 18
    color = rgba(255, 255, 255, 1.0)
    shadow_passes = 3
    shadow_boost = 0.9
}

label {
    text = cmd[] echo "$USER"
    position = 0, -10
    valign = center
    font_family = Segoe UI Semilight
    font_size = 28
    color = rgba(255, 255, 255, 1.0)
    shadow_passes = 3
    shadow_boost = 0.7
}

label {
    text = markuse arvuti asjad
    position = 84, 97
    valign = bottom
    font_family = Segoe UI Semilight
    font_size = 24
    color = rgba(255, 255, 255, 1.0)
    shadow_passes = 3
    shadow_boost = 0.9
}

image {
    path = ~/.mas/mas_incons/mas_general.png
    valign = bottom
    border_size = 0 
    size = 128
    position = -163,50
    shadow_passes = 3
    shadow_boost = 0.2
}

image {
    path = ~/.face
    rounding = 100
    size = 128
    border_size = 0
    position = 0, 100
}

animations {
    bezier = overshoot, 0.05, 0.9, 0.1, 1.1
    animation = inputFieldDots, 0
    animation = inputFieldFade, 0
    animation = inputFieldColors, 0
    enabled = true
}

input-field {
    monitor =
    size = 260, 40
    position = 70, -100
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 0

    font_family = Segoe UI Semilight
    font_color = $font_color
    
    placeholder_text = 
    check_color = $check_color
    fail_text = 
    dots_center = false
   
    text-align = left
    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = false
}

